application:
  challenge:
    path: '/exchange-rate/v1'

server:
  port: 8081


spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl'


